# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
language: node_js
node_js:
  - "0.10"

after_success:
# notify Docker Hub to make a new build
 -  >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"build": "true"}'
  https://registry.hub.docker.com/u/digitaldisciple/plurasight-docker-ci/trigger/$DOCKER_HUB_TOKEN/
