# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
language: node_js
node_js:
  - "0.10"

after_success:
# notify Docker Hub to make a new build
# [ "$TRAVIS_BRANCH" == "master" ]
  - $DOCKER_HUB_TRIGGER_URL + b6a7eb4a-7ba4-4b2d-97f7-e91399e706c1
